trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: projectName
    displayName: dev branch name
    default: "PacktProject"


variables:
  - name: applicationId
    value: "862e5a17-d38b-43ff-b24f-88a77f59623f"
  - name: tenantId
    value: "4ae51f31-XXX-YYYY-ZZZZ-5ece14d2c081" 
  - name: AADGroupForAdmin
    value: "FamilyGroup"
    
steps:
- script: |
   az login --service-principal \
      -u $(applicationId) \
      -p $(ClientSecret) \
      --tenant $(tenantId)
  displayName: Sign-in to Azure

- script: |
    set -e
    echo $(System.AccessToken) | az devops login --organization $(System.CollectionUri)
    az devops project create --name ${{ parameters.projectName }} --org $(System.CollectionUri)
    aadAdminGroupId=$(az ad group show --group $(AADGroupForAdmin) --query id -o tsv)
    echo "Admin group id: $aadAdminGroupId"
    azureDevopsAdminGroupDescriptor=$(az devops security group list --organization $(System.CollectionUri) --project ${{parameters.projectName}} | jq -r '.graphGroups[] | select(.displayName=="Project Administrators") | .descriptor')
    echo "Azure DevOps Admin Group Descriptor: $azureDevopsAdminGroupDescriptor"
    azureDevopContributorGroupId=$(az devops security group list --org $(System.CollectionUri) --project ${{parameters.projectName}} | jq -r '.graphGroups[] | select(.displayName=="Contributors") | .descriptor')
    echo "Azure DevOps Contributor Id: $azureDevopContributorGroupId"
    # Add the AAD group to the Administrators and Contributors groups in Azure DevOps (not working that's why using curl)
    # az devops security group membership add --group-id $azureDevopsAdminGroupId --member-id $aadAdminGroupId --org $(System.CollectionUri)
    collectionUri=$(System.CollectionUri)
    orgnamewithouthttps=${collectionUri//https:\/\//}
    curl -u :$(System.AccessToken) \
     -H "Content-Type: application/json" \
     -d "{\"originId\": \"$aadAdminGroupId\"}" \
     "https://vssps.$orgnamewithouthttps/_apis/graph/groups?groupDescriptors=$azureDevopsAdminGroupDescriptor&api-version=6.1-preview.1"


  displayName: 'create azure devops project in the same organization'
