trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
 solutionName: "PacktCopilotSolution"

steps:
- task: PowerPlatformToolInstaller@2
  inputs:
    DefaultVersion: true

- task: PowerPlatformPackSolution@2
  inputs:
    SolutionSourceFolder: '$(System.DefaultWorkingDirectory)/src/$(solutionName)'
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/Solution/$(solutionName).zip'
    SolutionType: 'Unmanaged'

- task: PowerPlatformChecker@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'dev-US_XXX_Y'
    FilesToAnalyze: '$(Build.ArtifactStagingDirectory)/Solution/$(solutionName).zip'
    RuleSet: '0ad12346-e108-40b8-a956-9a8f95ea18c9'
    ArtifactDestinationName: 'CodeAnalysisLogs'